import {
  Client,
  Editor,
  WorkProject,
  ClientPayment,
  EditorPayment,
  Expense,
  Activity,
  NotificationItem,
  BusinessSettings,
} from './types';

export const initialSettings: BusinessSettings = {
  businessName: 'Vidzyra',
  tagline: 'Your Social Media Partner',
  contactEmail: 'contact@vidzyra.com',
  contactPhone: '+91 98765 43210',
  whatsappNumber: '+919876543210',
  phone: '+91 98765 43210',
  email: 'contact@vidzyra.com',
  whatsapp: '+919876543210',
  currency: '₹',
  currencySymbol: '₹',
  receiptPrefix: 'VID-REC-2026',
  cloudFolderRoot: 'https://drive.google.com/drive/u/0/folders/vidzyra-master',
  portalWelcomeText: 'Welcome to your private Vidzyra portal. Manage files, review progress, and submit queries in one place.',
  logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100&auto=format&fit=crop&q=80',
  upiId: 'vidzyra@icici',
  bankDetails: {
    bankName: 'HDFC Bank',
    accountName: 'Vidzyra Media Agency LLP',
    accountNumber: '50200084920192',
    ifsc: 'HDFC0001234',
  },
  defaultClientRate: 2000,
  defaultEditorRate: 900,
  paymentMethods: ['UPI', 'Bank Transfer', 'Cash', 'Credit/Debit Card', 'PayPal', 'Cheque'],
  workTypes: ['Video Editing', 'Designing', 'Vertical Videos', 'Reels', 'YouTube Shorts', 'Poster', 'Website Design'],
  receiptNotes: 'Thank you for partnering with Vidzyra. All deliverables are subject to the master service agreement.',
  emailNotifications: true,
  whatsappNotifications: true,
  inAppAlerts: true,
  enableClientPortal: true,
  enableEditorPortal: true,
  autoApproveRevisions: false,
  googleDriveRootUrl: 'https://drive.google.com/drive/folders/vidzyra-root',
  dropboxRootUrl: 'https://www.dropbox.com/home/vidzyra',
  autoFolderCreation: true,
  adminName: 'Studio Director',
  adminEmail: 'admin@vidzyra.com',
  adminRole: 'Super Admin',
};

export const initialClients: Client[] = [
  {
    id: 'cli-1',
    name: 'Neon Peak Media',
    email: 'hello@neonpeak.io',
    phone: '+91 98231 44556',
    whatsapp: '+919823144556',
    clientType: 'Regular',
    defaultClientRate: 2500,
    notes: 'Premium agency client. Requires 4K 60FPS vertical export and bold typography.',
    portalToken: 'portal-client-neonpeak',
    portalStatus: 'Active',
    createdAt: '2026-08-01T10:00:00Z',
  },
  {
    id: 'cli-2',
    name: 'Fitness Aura (Rahul Mehta)',
    email: 'rahul@fitnessaura.co',
    phone: '+91 97112 88990',
    whatsapp: '+919711288990',
    clientType: 'Work',
    defaultClientRate: 1800,
    notes: 'Daily fitness workout shorts and nutrition reels. High energy sound design.',
    portalToken: 'portal-client-fitnessaura',
    portalStatus: 'Active',
    createdAt: '2026-08-05T11:30:00Z',
  },
  {
    id: 'cli-3',
    name: 'Aesthetic Living Interiors',
    email: 'projects@aestheticliving.in',
    phone: '+91 99887 11223',
    whatsapp: '+919988711223',
    clientType: 'Regular',
    defaultClientRate: 5000,
    notes: 'Architectural walk-throughs & cinematic home tours. Color grading is essential.',
    portalToken: 'portal-client-aestheticliving',
    portalStatus: 'Active',
    createdAt: '2026-08-10T09:15:00Z',
  },
  {
    id: 'cli-4',
    name: 'Apex Tech Talks',
    email: 'media@apextechtalks.com',
    phone: '+91 98450 33441',
    whatsapp: '+919845033441',
    clientType: 'Work',
    defaultClientRate: 2200,
    notes: 'Long-form podcast cutdowns into viral clips with engaging b-roll and emojis.',
    portalToken: 'portal-client-apextech',
    portalStatus: 'Active',
    createdAt: '2026-08-15T14:20:00Z',
  },
];

export const initialEditors: Editor[] = [
  {
    id: 'edt-1',
    name: 'Karan Sharma',
    email: 'karan.edits@vidzyra.team',
    contact: '+91 91234 56780',
    editorRate: 900,
    notes: 'Specialist in dynamic pacing, Alex Hormozi style captions, and sound design.',
    portalToken: 'portal-editor-karan',
    portalStatus: 'Active',
    createdAt: '2026-08-02T10:00:00Z',
  },
  {
    id: 'edt-2',
    name: 'Ananya Roy',
    email: 'ananya.visuals@vidzyra.team',
    contact: '+91 93456 78901',
    editorRate: 850,
    notes: 'Fast turnaround for fitness and lifestyle vertical videos. Excellent motion graphics.',
    portalToken: 'portal-editor-ananya',
    portalStatus: 'Active',
    createdAt: '2026-08-04T12:00:00Z',
  },
  {
    id: 'edt-3',
    name: 'Vikram Das',
    email: 'vikram.cine@vidzyra.team',
    contact: '+91 94567 89012',
    editorRate: 1200,
    notes: 'Senior colorist and cinematic long-form editor. Handles luxury and corporate work.',
    portalToken: 'portal-editor-vikram',
    portalStatus: 'Active',
    createdAt: '2026-08-08T15:00:00Z',
  },
  {
    id: 'edt-4',
    name: 'Priya Patel',
    email: 'priya.graphics@vidzyra.team',
    contact: '+91 95678 90123',
    editorRate: 800,
    notes: 'Thumbnails, poster designs, and animated graphics.',
    portalToken: 'portal-editor-priya',
    portalStatus: 'Active',
    createdAt: '2026-08-12T09:00:00Z',
  },
];

// Helper date strings
const now = new Date('2026-09-02T18:41:00');
const todayStr = '2026-09-02';
const tomorrowStr = '2026-09-03';
const yesterdayStr = '2026-09-01';
const futureStr = '2026-09-07';

export const initialProjects: WorkProject[] = [
  {
    id: 'wrk-101',
    clientId: 'cli-1',
    name: 'Neon Peak - 10 High-Paced Reels',
    workType: 'Reels',
    quantity: 10,
    clientRate: 2500,
    totalBilling: 25000,
    workDoneBy: 'Assigned',
    assignedTo: 'edt-1',
    editorRate: 900,
    dueDate: todayStr,
    notes: 'Hook within first 2 seconds, dynamic zoom-ins, SFX on every text pop.',
    status: 'In Progress',
    createdAt: '2026-08-28T09:00:00Z',
    userDownloadLink: 'https://drive.google.com/drive/folders/vidzyra-neonpeak-raw-01',
    userUploadLink: 'https://drive.google.com/drive/folders/vidzyra-neonpeak-edited-01',
    clientDownloadLink: 'https://drive.google.com/drive/folders/vidzyra-neonpeak-client-final',
    clientUploadLink: 'https://drive.google.com/drive/folders/vidzyra-neonpeak-client-upload',
    editorDownloadConfirmed: true,
    editorDownloadConfirmedAt: '2026-08-29T11:20:00Z',
    editorUploadConfirmed: false,
    clientUploadConfirmed: true,
    clientUploadConfirmedAt: '2026-08-28T10:15:00Z',
    clientDownloadConfirmed: false,
    revisionCount: 0,
    revisionStatus: 'No Revision',
    timeline: [
      { id: 'tm-1', person: 'Admin', action: 'Work Created', date: '2026-08-28', time: '09:00 AM', status: 'Pending' },
      { id: 'tm-2', person: 'Admin', action: 'Editor Assigned: Karan Sharma', date: '2026-08-28', time: '09:15 AM', status: 'Assigned' },
      { id: 'tm-3', person: 'Client (Neon Peak)', action: 'Raw Data Upload Confirmed', date: '2026-08-28', time: '10:15 AM', status: 'Raw Data Uploaded' },
      { id: 'tm-4', person: 'Editor (Karan Sharma)', action: 'Raw Data Download Confirmed', date: '2026-08-29', time: '11:20 AM', status: 'Downloaded' },
      { id: 'tm-5', person: 'Editor (Karan Sharma)', action: 'Status changed to In Progress', date: '2026-08-29', time: '11:30 AM', status: 'In Progress' },
    ],
  },
  {
    id: 'wrk-102',
    clientId: 'cli-2',
    name: 'Fitness Aura - 12 Workout Shorts',
    workType: 'YouTube Shorts',
    quantity: 12,
    clientRate: 1800,
    totalBilling: 21600,
    workDoneBy: 'Assigned',
    assignedTo: 'edt-2',
    editorRate: 850,
    dueDate: yesterdayStr, // Overdue
    notes: 'B-roll transitions between exercises. Neon yellow subtitle accents.',
    status: 'Revision Required',
    createdAt: '2026-08-24T14:00:00Z',
    userDownloadLink: 'https://drive.google.com/drive/folders/vidzyra-fit-raw-02',
    userUploadLink: 'https://drive.google.com/drive/folders/vidzyra-fit-edited-02',
    clientDownloadLink: 'https://drive.google.com/drive/folders/vidzyra-fit-client-final',
    clientUploadLink: 'https://drive.google.com/drive/folders/vidzyra-fit-client-upload',
    editorDownloadConfirmed: true,
    editorDownloadConfirmedAt: '2026-08-25T10:00:00Z',
    editorUploadConfirmed: true,
    editorUploadConfirmedAt: '2026-08-30T16:00:00Z',
    clientUploadConfirmed: true,
    clientUploadConfirmedAt: '2026-08-24T15:00:00Z',
    clientDownloadConfirmed: true,
    clientDownloadConfirmedAt: '2026-08-31T09:30:00Z',
    revisionCount: 1,
    revisionStatus: 'Revision Requested',
    revisionRequestedDate: '2026-08-31T11:00:00Z',
    revisionNotes: 'Please speed up the beat transitions between 0:15 and 0:28 and change subtitle color to yellow.',
    timeline: [
      { id: 'tm-10', person: 'Admin', action: 'Work Created', date: '2026-08-24', time: '02:00 PM', status: 'Pending' },
      { id: 'tm-11', person: 'Admin', action: 'Editor Assigned: Ananya Roy', date: '2026-08-24', time: '02:10 PM', status: 'Assigned' },
      { id: 'tm-12', person: 'Editor (Ananya Roy)', action: 'Edited Data Upload Confirmed', date: '2026-08-30', time: '04:00 PM', status: 'Uploaded' },
      { id: 'tm-13', person: 'Client (Fitness Aura)', action: 'Final Data Downloaded & Reviewing', date: '2026-08-31', time: '09:30 AM', status: 'Reviewing' },
      { id: 'tm-14', person: 'Client (Fitness Aura)', action: 'Marked Revision Required', date: '2026-08-31', time: '11:00 AM', status: 'Revision Required' },
    ],
  },
  {
    id: 'wrk-103',
    clientId: 'cli-3',
    name: 'Aesthetic Living - Luxury Villa Walkthrough',
    workType: 'Video Editing',
    quantity: 3,
    clientRate: 5000,
    totalBilling: 15000,
    workDoneBy: 'Me / Custom',
    assignedTo: null,
    editorRate: 0,
    dueDate: tomorrowStr,
    notes: 'Cinematic 4K grading, slow pan motion stabilizations, smooth drone footage integration.',
    status: 'In Progress',
    createdAt: '2026-08-29T10:00:00Z',
    userDownloadLink: '',
    userUploadLink: '',
    clientDownloadLink: 'https://drive.google.com/drive/folders/vidzyra-villa-final',
    clientUploadLink: 'https://drive.google.com/drive/folders/vidzyra-villa-raw',
    editorDownloadConfirmed: false,
    editorUploadConfirmed: false,
    clientUploadConfirmed: true,
    clientUploadConfirmedAt: '2026-08-29T11:00:00Z',
    clientDownloadConfirmed: false,
    revisionCount: 0,
    revisionStatus: 'No Revision',
    timeline: [
      { id: 'tm-20', person: 'Admin', action: 'Work Created (Me / Custom)', date: '2026-08-29', time: '10:00 AM', status: 'In Progress' },
      { id: 'tm-21', person: 'Client (Aesthetic Living)', action: 'Raw 4K Footage Upload Confirmed', date: '2026-08-29', time: '11:00 AM', status: 'Raw Data Uploaded' },
    ],
  },
  {
    id: 'wrk-104',
    clientId: 'cli-4',
    name: 'Apex Tech - AI Insights Series',
    workType: 'Vertical Videos',
    quantity: 8,
    clientRate: 2200,
    totalBilling: 17600,
    workDoneBy: 'Assigned',
    assignedTo: 'edt-3',
    editorRate: 1200,
    dueDate: futureStr,
    notes: 'Sound design with tech whooshes and kinetic typography.',
    status: 'Completed',
    createdAt: '2026-08-20T10:00:00Z',
    userDownloadLink: 'https://drive.google.com/drive/folders/vidzyra-apex-raw',
    userUploadLink: 'https://drive.google.com/drive/folders/vidzyra-apex-edited',
    clientDownloadLink: 'https://drive.google.com/drive/folders/vidzyra-apex-client-final',
    clientUploadLink: 'https://drive.google.com/drive/folders/vidzyra-apex-client-raw',
    editorDownloadConfirmed: true,
    editorUploadConfirmed: true,
    clientUploadConfirmed: true,
    clientDownloadConfirmed: true,
    revisionCount: 0,
    revisionStatus: 'No Revision',
    timeline: [
      { id: 'tm-30', person: 'Admin', action: 'Work Created', date: '2026-08-20', time: '10:00 AM', status: 'Pending' },
      { id: 'tm-31', person: 'Admin', action: 'Editor Assigned: Vikram Das', date: '2026-08-20', time: '10:30 AM', status: 'Assigned' },
      { id: 'tm-32', person: 'Editor (Vikram Das)', action: 'Edited Data Upload Confirmed', date: '2026-08-25', time: '05:00 PM', status: 'Uploaded' },
      { id: 'tm-33', person: 'Client (Apex Tech Talks)', action: 'Data Downloaded & Approved', date: '2026-08-26', time: '03:00 PM', status: 'Approved' },
      { id: 'tm-34', person: 'Admin', action: 'Marked Completed & Delivered', date: '2026-08-26', time: '03:30 PM', status: 'Completed' },
    ],
  },
];

export const initialClientPayments: ClientPayment[] = [
  {
    id: 'pay-c1',
    receiptNumber: 'VID-REC-2026-0001',
    clientId: 'cli-1',
    workId: 'wrk-101',
    amount: 15000,
    date: '2026-08-28',
    paymentMethod: 'UPI',
    referenceNumber: 'UPI/98127391823/OKAXIS',
    paymentType: 'Advance',
    notes: 'Advance 60% payment for 10 IG Reels Campaign.',
    createdAt: '2026-08-28T09:30:00Z',
  },
  {
    id: 'pay-c2',
    receiptNumber: 'VID-REC-2026-0002',
    clientId: 'cli-2',
    workId: 'wrk-102',
    amount: 10000,
    date: '2026-08-24',
    paymentMethod: 'Bank Transfer',
    referenceNumber: 'NEFT-HDFC-991820491',
    paymentType: 'Advance',
    notes: 'Advance for Workout Shorts package.',
    createdAt: '2026-08-24T14:30:00Z',
  },
  {
    id: 'pay-c3',
    receiptNumber: 'VID-REC-2026-0003',
    clientId: 'cli-4',
    workId: 'wrk-104',
    amount: 17600,
    date: '2026-08-27',
    paymentMethod: 'UPI',
    referenceNumber: 'UPI/77162534120/OKICICI',
    paymentType: 'Final',
    notes: 'Full payment cleared after client approval.',
    createdAt: '2026-08-27T16:00:00Z',
  },
];

export const initialEditorPayments: EditorPayment[] = [
  {
    id: 'pay-e1',
    receiptNumber: 'VID-EDT-2026-0001',
    editorId: 'edt-3',
    workId: 'wrk-104',
    amount: 9600, // 8 * 1200
    date: '2026-08-27',
    paymentMethod: 'UPI',
    referenceNumber: 'UPI/EDT/9102830192',
    paymentType: 'Final',
    notes: 'Full payment for AI Insights series editing.',
    createdAt: '2026-08-27T17:00:00Z',
  },
  {
    id: 'pay-e2',
    receiptNumber: 'VID-EDT-2026-0002',
    editorId: 'edt-1',
    workId: 'wrk-101',
    amount: 4500, // 50% advance for 10 reels @ 900
    date: '2026-08-29',
    paymentMethod: 'Bank Transfer',
    referenceNumber: 'IMPS-SBI-0091829',
    paymentType: 'Advance',
    notes: 'Advance payment for Neon Peak batch.',
    createdAt: '2026-08-29T12:00:00Z',
  },
];

export const initialExpenses: Expense[] = [
  {
    id: 'exp-1',
    name: 'Adobe Creative Cloud Team License',
    category: 'Software / Tools',
    amount: 5500,
    date: '2026-08-01',
    notes: 'Monthly subscription for agency workstations.',
    createdAt: '2026-08-01T08:00:00Z',
  },
  {
    id: 'exp-2',
    name: 'Epidemic Sound Agency Music License',
    category: 'Assets / Music',
    amount: 2800,
    date: '2026-08-05',
    notes: 'Commercial music licensing for client reels.',
    createdAt: '2026-08-05T09:00:00Z',
  },
  {
    id: 'exp-3',
    name: 'Google One 2TB Cloud Storage',
    category: 'Software / Tools',
    amount: 650,
    date: '2026-08-10',
    notes: 'Raw client footage backup and staging.',
    createdAt: '2026-08-10T10:00:00Z',
  },
];

export const initialActivities: Activity[] = [
  {
    id: 'act-1',
    who: 'Client (Fitness Aura)',
    action: 'Revision requested',
    what: 'Requested beat timing revision on Workout Shorts #4 and #7',
    when: '2026-08-31 11:00 AM',
    timestamp: Date.parse('2026-08-31T11:00:00Z'),
    entityType: 'revision',
    entityId: 'wrk-102',
    clientId: 'cli-2',
    editorId: 'edt-2',
  },
  {
    id: 'act-2',
    who: 'Editor (Karan Sharma)',
    action: 'Raw data downloaded',
    what: 'Confirmed download of raw reels data for Neon Peak Media',
    when: '2026-08-29 11:20 AM',
    timestamp: Date.parse('2026-08-29T11:20:00Z'),
    entityType: 'confirmation',
    entityId: 'wrk-101',
    clientId: 'cli-1',
    editorId: 'edt-1',
  },
  {
    id: 'act-3',
    who: 'Admin',
    action: 'Payment received',
    what: 'Received ₹15,000 advance from Neon Peak Media (VID-REC-2026-0001)',
    when: '2026-08-28 09:30 AM',
    timestamp: Date.parse('2026-08-28T09:30:00Z'),
    entityType: 'payment',
    entityId: 'pay-c1',
    clientId: 'cli-1',
  },
  {
    id: 'act-4',
    who: 'Editor (Vikram Das)',
    action: 'Edited data uploaded',
    what: 'Uploaded all 8 final cuts for Apex Tech Talks AI series',
    when: '2026-08-25 05:00 PM',
    timestamp: Date.parse('2026-08-25T17:00:00Z'),
    entityType: 'file',
    entityId: 'wrk-104',
    clientId: 'cli-4',
    editorId: 'edt-3',
  },
  {
    id: 'act-5',
    who: 'Admin',
    action: 'Portal activated',
    what: 'Activated client portal for Aesthetic Living Interiors',
    when: '2026-08-10 09:15 AM',
    timestamp: Date.parse('2026-08-10T09:15:00Z'),
    entityType: 'portal',
    entityId: 'cli-3',
    clientId: 'cli-3',
  },
];

export const initialNotifications: NotificationItem[] = [
  {
    id: 'notif-1',
    type: 'revision',
    message: 'Fitness Aura requested revision for "Fitness Aura - 12 Workout Shorts"',
    relatedClientId: 'cli-2',
    relatedEditorId: 'edt-2',
    relatedWorkId: 'wrk-102',
    date: '2026-08-31',
    time: '11:00 AM',
    timestamp: Date.parse('2026-08-31T11:00:00Z'),
    read: false,
  },
  {
    id: 'notif-2',
    type: 'confirmation',
    message: 'Editor Karan Sharma confirmed raw data downloaded for Neon Peak Media',
    relatedClientId: 'cli-1',
    relatedEditorId: 'edt-1',
    relatedWorkId: 'wrk-101',
    date: '2026-08-29',
    time: '11:20 AM',
    timestamp: Date.parse('2026-08-29T11:20:00Z'),
    read: false,
  },
  {
    id: 'notif-3',
    type: 'payment',
    message: 'Client payment of ₹15,000 received from Neon Peak Media',
    relatedClientId: 'cli-1',
    relatedPaymentId: 'pay-c1',
    date: '2026-08-28',
    time: '09:30 AM',
    timestamp: Date.parse('2026-08-28T09:30:00Z'),
    read: false,
  },
  {
    id: 'notif-4',
    type: 'work',
    message: 'Work "Fitness Aura - 12 Workout Shorts" is overdue (Due date was 2026-09-01)',
    relatedClientId: 'cli-2',
    relatedEditorId: 'edt-2',
    relatedWorkId: 'wrk-102',
    date: '2026-09-02',
    time: '09:00 AM',
    timestamp: Date.parse('2026-09-02T09:00:00Z'),
    read: false,
  },
];
